language: android

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
  licenses:
    - android-sdk-license-.+

script:
  - chmod +x gradlew
  - ./gradlew clean build test ktlintCheck
